# 1. Import Library

In [26]:
import pandas as pd
import pickle

# 2. Load Data

In [27]:
# load model terbaik
with open('best_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# 3. Prediction 1

In [28]:
# membuat data inference baru
data_inf = pd.DataFrame({

    'gender': ['Male'],
    'SeniorCitizen': [0],
    'Partner': ['Yes'],
    'Dependents': ['No'],
    'tenure': [12],
    'PhoneService': ['Yes'],
    'MultipleLines': ['No'],
    'InternetService': ['Fiber optic'],
    'OnlineSecurity': ['No'],
    'OnlineBackup': ['Yes'],
    'DeviceProtection': ['No'],
    'TechSupport': ['No'],
    'StreamingTV': ['Yes'],
    'StreamingMovies': ['Yes'],
    'Contract': ['Month-to-month'],
    'PaperlessBilling': ['Yes'],
    'PaymentMethod': ['Electronic check'],
    'MonthlyCharges': [85.5],
    'TotalCharges': [1026.0]

})

# tampilkan data inference
data_inf

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Male,0,Yes,No,12,Yes,No,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,85.5,1026.0

In [39]:
# prediksi churn
pred_inf = loaded_model.predict(data_inf)

# probabilitas churn
pred_prob = loaded_model.predict_proba(data_inf)

print("Prediction :", pred_inf[0])
print(f"Probability Non-Churn : {pred_prob[0][0]:.2%}")
print(f"Probability Churn     : {pred_prob[0][1]:.2%}")

Prediction : 1
Probability Non-Churn : 21.79%
Probability Churn     : 78.21%

In [30]:
# interpretasi hasil prediksi
if pred_inf[0] == 1:
    print("Customer diprediksi akan churn")
else:
    print("Customer diprediksi tidak churn")

Customer diprediksi akan churn

Insight:

>- Berdasarkan hasil inference, model memprediksi bahwa pelanggan akan melakukan churn dengan probabilitas sebesar 78.16%. Hal ini menunjukkan bahwa model memiliki tingkat keyakinan yang cukup tinggi terhadap prediksi churn yang dihasilkan.
>
>- Prediksi tersebut dipengaruhi oleh beberapa karakteristik pelanggan yang sebelumnya juga terlihat memiliki hubungan dengan churn pada tahap EDA dan feature importance. Pelanggan menggunakan kontrak bulanan (month-to-month), metode pembayaran electronic check, serta tidak menggunakan layanan tambahan seperti OnlineSecurity dan TechSupport.
>
>- Selain itu, pelanggan juga memiliki tenure yang masih relatif rendah, yaitu 12 bulan, yang menunjukkan bahwa pelanggan belum memiliki loyalitas yang kuat terhadap layanan perusahaan. Kombinasi faktor-faktor tersebut menyebabkan pelanggan memiliki risiko churn yang cukup tinggi menurut model yang telah dibuat.
>
>- Pelanggan dengan karakteristik seperti ini dapat menjadi prioritas utama dalam strategi retensi karena memiliki risiko churn yang cukup tinggi menurut model.

#  4. Prediction 2

In [31]:
# membuat data inference pelanggan non-churn
data_inf_non_churn = pd.DataFrame({

    'gender': ['Male'],
    'SeniorCitizen': [0],
    'Partner': ['Yes'],
    'Dependents': ['Yes'],
    'tenure': [60],
    'PhoneService': ['Yes'],
    'MultipleLines': ['Yes'],
    'InternetService': ['DSL'],
    'OnlineSecurity': ['Yes'],
    'OnlineBackup': ['Yes'],
    'DeviceProtection': ['Yes'],
    'TechSupport': ['Yes'],
    'StreamingTV': ['No'],
    'StreamingMovies': ['No'],
    'Contract': ['Two year'],
    'PaperlessBilling': ['No'],
    'PaymentMethod': ['Bank transfer (automatic)'],
    'MonthlyCharges': [55.2],
    'TotalCharges': [3312.0]

})

# tampilkan data
data_inf_non_churn

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Male,0,Yes,Yes,60,Yes,Yes,DSL,Yes,Yes,Yes,Yes,No,No,Two year,No,Bank transfer (automatic),55.2,3312.0

In [38]:
# prediksi 
pred_non_churn = loaded_model.predict(data_inf_non_churn)

# probabilitas prediksi
prob_non_churn = loaded_model.predict_proba(data_inf_non_churn)

print("Prediction :", pred_non_churn[0])
print(f"Probability Non-Churn : {prob_non_churn[0][0]:.2%}")
print(f"Probability Churn     : {prob_non_churn[0][1]:.2%}")

Prediction : 0
Probability Non-Churn : 90.63%
Probability Churn     : 9.37%

In [33]:
# interpretasi hasil
if pred_non_churn[0] == 1:
    print("Customer diprediksi akan churn")
else:
    print("Customer diprediksi tidak churn")

Customer diprediksi tidak churn

Insight:

>- Berdasarkan hasil inference, model memprediksi bahwa pelanggan tidak akan melakukan churn dengan probabilitas sebesar 90.23%. Hal ini menunjukkan bahwa model memiliki tingkat keyakinan yang cukup tinggi bahwa pelanggan akan tetap menggunakan layanan perusahaan.
>
>- Prediksi non-churn ini dipengaruhi oleh beberapa karakteristik pelanggan yang sebelumnya juga terlihat memiliki hubungan dengan loyalitas pelanggan. Pelanggan memiliki tenure yang tinggi, yaitu 60 bulan, menggunakan kontrak jangka panjang (two year), serta menggunakan berbagai layanan tambahan seperti OnlineSecurity, OnlineBackup, DeviceProtection, dan TechSupport.
>
>- Selain itu, metode pembayaran otomatis melalui bank transfer juga menjadi salah satu faktor yang cenderung berkaitan dengan tingkat churn yang lebih rendah. Kombinasi faktor-faktor tersebut menunjukkan bahwa pelanggan memiliki tingkat keterikatan dan loyalitas yang lebih tinggi terhadap layanan perusahaan sehingga kemungkinan churn menjadi rendah menurut model yang telah dibuat.
>
>- Karakteristik tersebut menunjukkan bahwa pelanggan memiliki loyalitas yang cukup baik sehingga perusahaan dapat lebih fokus mempertahankan kualitas layanan.

# 5. Prediction 3

In [34]:
# data customer dengan karakteristik menengah
data_inf_middle = pd.DataFrame({

    'gender': ['Female'],
    'SeniorCitizen': [0],
    'Partner': ['No'],
    'Dependents': ['No'],
    'tenure': [24],
    'PhoneService': ['Yes'],
    'MultipleLines': ['No'],
    'InternetService': ['Fiber optic'],
    'OnlineSecurity': ['No'],
    'OnlineBackup': ['Yes'],
    'DeviceProtection': ['Yes'],
    'TechSupport': ['No'],
    'StreamingTV': ['Yes'],
    'StreamingMovies': ['No'],
    'Contract': ['One year'],
    'PaperlessBilling': ['Yes'],
    'PaymentMethod': ['Credit card (automatic)'],
    'MonthlyCharges': [75.5],
    'TotalCharges': [1812.0]

})

# tampilkan data
data_inf_middle

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,No,No,24,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,No,One year,Yes,Credit card (automatic),75.5,1812.0

In [37]:
# prediksi
pred_middle = loaded_model.predict(data_inf_middle)

# probabilitas
prob_middle = loaded_model.predict_proba(data_inf_middle)

print("Prediction :", pred_middle[0])
print(f"Probability Non-Churn : {prob_middle[0][0]:.2%}")
print(f"Probability Churn     : {prob_middle[0][1]:.2%}")

Prediction : 0
Probability Non-Churn : 83.05%
Probability Churn     : 16.95%

In [36]:
# interpretasi hasil
if pred_middle[0] == 1:
    print("Customer diprediksi akan churn")
else:
    print("Customer diprediksi tidak churn")

Customer diprediksi tidak churn

Insight:

>- Berdasarkan hasil inference, model memprediksi bahwa pelanggan tidak akan melakukan churn dengan probabilitas sebesar 83.58%, sementara probabilitas churn berada pada angka 16.42%. Hal ini menunjukkan bahwa pelanggan masih cenderung bertahan menggunakan layanan perusahaan meskipun memiliki beberapa karakteristik yang berpotensi meningkatkan risiko churn.
>
>- Pelanggan menggunakan layanan Fiber Optic dan belum menggunakan fitur OnlineSecurity maupun TechSupport, yang sebelumnya diketahui memiliki hubungan dengan churn. Namun, risiko tersebut tampaknya masih dapat ditekan karena pelanggan menggunakan kontrak satu tahun (One year) serta metode pembayaran otomatis menggunakan Credit Card.
>
>- Selain itu, tenure pelanggan yang sudah mencapai 24 bulan juga menunjukkan bahwa pelanggan telah cukup lama menggunakan layanan perusahaan sehingga tingkat loyalitasnya cenderung lebih baik dibandingkan pelanggan baru. Oleh karena itu, meskipun terdapat beberapa faktor risiko churn, model tetap memprediksi pelanggan sebagai non-churn dengan tingkat keyakinan yang cukup tinggi.